"""update db 3.0

Revision ID: 0173046e4abf
Revises: 0cfcf85365db
Create Date: 2024-04-03 23:37:16.420130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0173046e4abf'
down_revision = '0cfcf85365db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasiltest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nip_nis', sa.String(length=15), nullable=True),
    sa.Column('visual', sa.Integer(), nullable=True),
    sa.Column('auditorial', sa.Integer(), nullable=True),
    sa.Column('kinestetik', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode_room', sa.String(length=10), nullable=True),
    sa.Column('nip_nis', sa.String(length=15), nullable=True),
    sa.Column('nama_room', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kode_room', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('kode_room')

    op.drop_table('room')
    op.drop_table('hasiltest')
    # ### end Alembic commands ###
