"""update db 7.0

Revision ID: 38f772326cdd
Revises: 592d503c708d
Create Date: 2024-04-05 07:24:31.152179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f772326cdd'
down_revision = '592d503c708d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roomsiswa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode_room', sa.String(length=10), nullable=True),
    sa.Column('nip_nis', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['kode_room'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nip_nis'])
        batch_op.drop_column('kode_room')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kode_room', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('roomsiswa')
    # ### end Alembic commands ###
